ARM: cmpxchg: Fix compilation error caused by undeclared cmpxchg_emu_u8
Include linux/cmpxchg-emu.h to fix compilation error:

  CC      kernel/bounds.s
In file included from arch/arm/include/asm/atomic.h:16,
                 from include/linux/atomic.h:7,
                 from include/asm-generic/bitops/lock.h:5,
                 from arch/arm/include/asm/bitops.h:245,
                 from include/linux/bitops.h:63,
                 from include/linux/log2.h:12,
                 from kernel/bounds.c:13:
arch/arm/include/asm/cmpxchg.h: In function '__cmpxchg':
arch/arm/include/asm/cmpxchg.h:167:26: error: implicit declaration of function 'cmpxchg_emu_u8' [-Wimplicit-function-declaration]
  167 |                 oldval = cmpxchg_emu_u8((volatile u8 *)ptr, old, new);
      |                          ^~~~~~~~~~~~~~

Fixes: 6ba3d5014d24 ("ARM: Emulate one-byte cmpxchg")
Signed-off-by: Peter Ujfalusi <peter.ujfalusi@gmail.com>